### ISSUE TITLE
init call and DST

### ISSUE THREAD

**Issue by jaycollett** [sfrwmaker/sunMoon#1]
Not sure if this is an issue with the code or with the example code but daylight savings time changes would be a problem for the code as in the example. Does one just execute the init inside the loop after identifying the correct offset or is there a method to adjust for DST before executing the sunRise and sunSet calls?

**Comment by sfrwmaker** [comment]
It would be an issue in usual case. Since we are dealing with arduino, timezones are difficult to implement inside the microcontroller memory. I sudgest to change 'time shift from GMT' parameter accordingly to your timezone rules.

**Comment by jaycollett** [comment]
Ok, is it safe to call sm.init inside a method that would get called more than once? I'm using the TimeZone library to adjust the UTC time stored in a RTC and then based on the current offset, calling the sm.init method with the correct offset.

**Comment by sfrwmaker** [comment]
Absolutely safe.

**Comment by jaycollett** [comment]
Thanks for the quick feedback on this issue. Awesome library, great work!
