### ISSUE TITLE
how to call sunset and sunrise function

### ISSUE THREAD

**Issue by picposter** [sfrwmaker/sunMoon#3]
Hello,
this is no issue, but i didn´t know how to ask for help otherwise:

can you give me an example how to read out the sunrise and sunset values in variables like hour minutes and seconds ?

This library would be perfect, but i don´t unterstand it completely.

thank you very much

Picposter

**Comment by sfrwmaker** [comment]
Hello!

One example available on hacksters:
https://www.hackster.io/sfrwmaker/sun-and-moon-times-cd1629 or in the
repository:
https://github.com/sfrwmaker/sunMoon/blob/master/examples/sunrise.ino

First, you should initialize the class instane by
bool init(int Timezone, float Latitude, float Longitude);

then you can use

time_t sunRise(time_t date = 0); and time_t sunSet(time_t date = 0); to get
the UNIX format sunrise and sunset time. If you call these functions
without argument, they return the times for the current day.
Make sure that now() returns the correct data. OR you can use your own UNIX
time argument to get sunrise and sunset times for that date.

Please, check the source code:
time_t sunMoon::sunTime(bool sunRise, time_t date) { if (date == 0) date =
now();



2017-11-29 7:59 GMT+03:00 picposter <notifications@github.com>:

**Comment by picposter** [comment]
Hello,
Alright, i understood it how it Workshop. Thank you.

Another question:
Will it use Summer/Winter time ? Or do i have to

**Comment by picposter** [comment]
Another question:
Will it use Summer/Winter time ? Or do i have to add this Option on my own ?

Thanks for your Support
Picposter

**Comment by sfrwmaker** [comment]
Hello!

The class has time shift ftom Greenwich in minutes only. The summer/winter
time is not supported by the library. You cn support it by changing the
time shift value.

I supposed, that the arduino controler has limited amount of the resources
to support dst.

5 Дек 2017 г. 23:22 пользователь "picposter" <notifications@github.com>
написал:

**Comment by fani625** [comment]
Hello.

Thank for this great effort. I want to print only sun time on LCD 20*4 (LiquidCrystal_I2C). Your explanation regarding the library is higher than my level. Can you add one more example for call only sun time in loops with normal argument like if else .etc.
  
Thanks again
