### ISSUE TITLE
Adding more decimals to moon age

### ISSUE THREAD

**Issue by q24h** [sfrwmaker/sunMoon#4]
Greetings, this light weight library is working great for me, I wanted to ask how I can go about adding a couple of decimals, specifically to the moon age, so I can use it for more a more accurate moon phase calculation, I couldn't figure it out in the code..

**Comment by sfrwmaker** [comment]
You can add yet another function, like this:
float sunMoon::moonDayF(time_t date) {

 float IP = normalize((julianDay(date) - 2451550.1) / 29.530588853);
 IP *= 29.530588853;
 return IP;
}

**Comment by Jxid** [comment]
Can you explain it with an example please?
I am interesting in displaying moon age with 2 decimals.
Thank you.
Yannis
