### ISSUE TITLE
Request for Examples to your code

### ISSUE THREAD

**Issue by davidsvarrer** [sfrwmaker/sunMoon#6]
Dear Sfrwmaker, 

I hereby request that you make a description of your good algorithms for this SunMoon module you have made. I am in doubt what the float t parameter is doing, and how it shall be formatted, (I assume that it is a time parameter - however - I do not understand if it is supposed to be a Julian time, a hour/minute/second time, a full year/month/day/hour/minute/second time, or a Unix time - or seconds-since-epoch, and so on. So it would be wonderful with some examples for us mortals :-)

If you can explain it to me, just by a line or two, then I wouldn't mind updating the software nicely, make good comments, update the example etc. 

Let me know. My email is ds@rain.yt, and I respond typically within 24 hours.

Sincerely
David Svarrer

**Comment by davidsvarrer** [comment]
Dear Sfrwmaker - I am still interested in your explanation. 

I am creating a small scale solar concentrator, and while I am good in the mechanics, I am not thaaaaat good in the mathematics. 

So your help would be warmly welcomed. 

Have a good time, a good day, stay safe from Covid19 (Remember to take your vitamin D3 - 800 IU per day for an adult)...

David Svarrer

**Comment by sfrwmaker** [comment]
Hello!
Sorry, i cannot explain the source code. I do not understand it in the details. :)
Some years ago i have found some article In the Internet that describe the way to calculate sunrise and sunset times. Yet, i have used some freeware code as a reference. It is working and it is compact enough to fit the Arduino memory.
