### ISSUE TITLE
wrong calculation

### ISSUE THREAD

**Issue by ulegan** [sfrwmaker/sunMoon#8]
Line 78 in sunMoon.cpp should be:
`  int N3 = 1 + (year(date) - 4 * (year(date) / 4) + 2) / 3;`
not:
`  int N3 = 1 + (year(date) - 4 * (year(date)) / 4 + 2) / 3;`

**Comment by sfrwmaker** [comment]
Fixed. Thank you very much.

**Comment by najmulhaq** [comment]
Does not seems to calculate correct values for Mumbai, IN (Lat/Long 18°57'N / 72°50'E, GMT+5,5) , can you please check to get it fixed.
Reference times can be taken from https://www.timeanddate.com/worldclock/india/mumbai

**Comment by sfrwmaker** [comment]
Hello!
Can you tell me how do you use the library and what is the wrong values?

**Comment by najmulhaq** [comment]
I used your library as per example & gave lon/lat & timezone values for Mumbai & compared with the values from https://www.timeanddate.com/worldclock/india/mumbai & it does not match

**Comment by sfrwmaker** [comment]
Here is the coordinates: https://www.latlong.net/place/mumbai-maharashtra-india-27236.html
#define OUR_latitude    19.076090               // Mumbai
#define OUR_longtitude  72.877426
#define OUR_timezone    330 
But we can use the ones, that published on site you mentioned: 18*57', 72*50'
#define OUR_latitude    18.95
#define OUR_longtitude  72.83
#define OUR_timezone    330                     // localtime with UTC difference in minutes

RTC has set the system time
Today is  9-06-2020 10:48:31
Today is 2459010 Julian day
Moon age is 19day(s)
Today sunrise and sunset:  9-06-2020 06:00:36;  9-06-2020 19:15:26
Specific date was  3-08-2016 12:12:00
Specific date sunrise and sunset was: Julian day of specific date was 2457604
Moon age was 1day(s)
 3-08-2016 06:16:24;  3-08-2016 19:12:54

On site you mentioned: (https://www.timeanddate.com/worldclock/india/mumbai)
Sunrise 6:00, Sunset 19:15.

Where is the issue?

**Comment by najmulhaq** [comment]
Sorry, my bad. I was not assigning dates properly before the call.
Fixed it, now its working absolutely fine.

Thank you very much for your revert...
